### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Nicolol1234** [jpenilla/better-fabric-console#22]
Putting the mod made my server crash, here are the logs:

[13:27:28 ERROR] [main]: [FabricLoader] Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'net.kyori.adventure.util.Codec net.kyori.adventure.util.Codec.codec(net.kyori.adventure.util.Codec$Decoder, net.kyori.adventure.util.Codec$Encoder)'
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:464) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.19.jar:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.util.Codec net.kyori.adventure.util.Codec.codec(net.kyori.adventure.util.Codec$Decoder, net.kyori.adventure.util.Codec$Encoder)'
        at net.kyori.adventure.platform.fabric.impl.NBTLegacyHoverEventSerializer.<clinit>(NBTLegacyHoverEventSerializer.java:43) ~[adventure-platform-fabric-5.5.0-SNAPSHOT-a245f1361324946.jar:?]
        at net.kyori.adventure.platform.fabric.impl.service.GsonComponentSerializerProviderImpl.lambda$builder$0(GsonComponentSerializerProviderImpl.java:52) ~[adventure-platform-fabric-5.5.0-SNAPSHOT-a245f1361324946.jar:?]
        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl$BuilderImpl.<init>(GsonComponentSerializerImpl.java:117) ~[Cardboard-1.19.2.jar:?]
        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializer.builder(GsonComponentSerializer.java:77) ~[Cardboard-1.19.2.jar:?]
        at net.kyori.adventure.platform.fabric.impl.service.GsonComponentSerializerProviderImpl.gson(GsonComponentSerializerProviderImpl.java:36) ~[adventure-platform-fabric-5.5.0-SNAPSHOT-a245f1361324946.jar:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl$Instances.<clinit>(GsonComponentSerializerImpl.java:48) ~[Cardboard-1.19.2.jar:?]
        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializer.gson(GsonComponentSerializer.java:54) ~[Cardboard-1.19.2.jar:?]
        at net.minecraft.network.chat.Component$Serializer.handler$zzg000$adventure-platform-fabric$adventure$injectGson(Component.java:1064) ~[?:?]
        at net.minecraft.network.chat.Component$Serializer.lambda$static$0(Component.java:155) ~[?:?]
        at net.minecraft.Util.make(Util.java:444) ~[?:?]
        at net.minecraft.network.chat.Component$Serializer.<clinit>(Component.java:153) ~[?:?]
        at net.minecraft.server.packs.metadata.pack.PackMetadataSectionSerializer.fromJson(PackMetadataSectionSerializer.java:12) ~[?:?]
        at net.minecraft.server.packs.metadata.pack.PackMetadataSectionSerializer.fromJson(PackMetadataSectionSerializer.java:9) ~[?:?]
        at net.minecraft.server.packs.AbstractPackResources.getMetadataFromStream(AbstractPackResources.java:84) ~[?:?]
        at net.fabricmc.fabric.impl.resource.loader.FabricModResourcePack.getMetadataSection(FabricModResourcePack.java:80) ~[fabric-resource-loader-v0-0.8.4+edbdcddb90-99f22ff1e27d1983.jar:?]
        at net.minecraft.server.packs.repository.Pack.create(Pack.java:36) ~[?:?]
        at net.fabricmc.fabric.impl.resource.loader.ModResourcePackCreator.loadPacks(ModResourcePackCreator.java:78) ~[fabric-resource-loader-v0-0.8.4+edbdcddb90-99f22ff1e27d1983.jar:?]
        at net.fabricmc.fabric.impl.resource.loader.ModResourcePackCreator.register(ModResourcePackCreator.java:52) ~[fabric-resource-loader-v0-0.8.4+edbdcddb90-99f22ff1e27d1983.jar:?]
        at net.fabricmc.fabric.impl.resource.loader.ModResourcePackUtil.createDefaultDataPackSettings(ModResourcePackUtil.java:113) ~[fabric-resource-loader-v0-0.8.4+edbdcddb90-99f22ff1e27d1983.jar:?]
        at net.minecraft.server.Main.redirect$bej000$fabric-resource-loader-v0$replaceDefaultDataPackSettings(Main.java:1532) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:152) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
        ... 3 more

**Comment by jpenilla** [comment]
probably a cardboard issue, but neither servers using cardboard nor outdated versions of BFC are supported.
