### ISSUE TITLE
Game crash at startup

### ISSUE THREAD

**Issue by Nicolol1234** [jpenilla/better-fabric-console#28]
here is the stacktrace:

``` [14:33:55 ERROR] [main]: [FabricLoader] Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'net.kyori.adventure.util.Codec net.kyori.adventure.util.Codec.codec(net.kyori.adventure.util.Codec$Decoder, net.kyori.adventure.util.Codec$Encoder)'
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.14.22-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.util.Codec net.kyori.adventure.util.Codec.codec(net.kyori.adventure.util.Codec$Decoder, net.kyori.adventure.util.Codec$Encoder)'
        at net.kyori.adventure.platform.fabric.impl.NBTLegacyHoverEventSerializer.<clinit>(NBTLegacyHoverEventSerializer.java:43) ~[adventure-platform-fabric-5.9.0-901d95766a18a80f.jar:?]
        at net.kyori.adventure.platform.fabric.impl.service.GsonComponentSerializerProviderImpl.lambda$builder$0(GsonComponentSerializerProviderImpl.java:52) ~[adventure-platform-fabric-5.9.0-901d95766a18a80f.jar:?]
        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl$BuilderImpl.<init>(GsonComponentSerializerImpl.java:117) ~[Cardboard-1.20.jar:?]
        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializer.builder(GsonComponentSerializer.java:77) ~[Cardboard-1.20.jar:?]
        at net.kyori.adventure.platform.fabric.impl.service.GsonComponentSerializerProviderImpl.gson(GsonComponentSerializerProviderImpl.java:36) ~[adventure-platform-fabric-5.9.0-901d95766a18a80f.jar:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl$Instances.<clinit>(GsonComponentSerializerImpl.java:48) ~[Cardboard-1.20.jar:?]
        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializer.gson(GsonComponentSerializer.java:54) ~[Cardboard-1.20.jar:?]
        at net.minecraft.network.chat.Component$Serializer.handler$zzf000$adventure-platform-fabric$adventure$injectGson(Component.java:1074) ~[?:?]
        at net.minecraft.network.chat.Component$Serializer.lambda$static$0(Component.java:155) ~[?:?]
        at net.minecraft.Util.make(Util.java:432) ~[?:?]
        at net.minecraft.network.chat.Component$Serializer.<clinit>(Component.java:153) ~[?:?]
        at net.minecraft.server.packs.metadata.pack.PackMetadataSectionSerializer.fromJson(PackMetadataSectionSerializer.java:13) ~[?:?]
        at net.minecraft.server.packs.metadata.pack.PackMetadataSectionSerializer.fromJson(PackMetadataSectionSerializer.java:10) ~[?:?]
        at net.minecraft.server.packs.AbstractPackResources.getMetadataFromStream(AbstractPackResources.java:53) ~[?:?]
        at net.fabricmc.fabric.impl.resource.loader.FabricModResourcePack.getMetadataSection(FabricModResourcePack.java:70) ~[fabric-resource-loader-v0-0.11.9+132c48c177-f47fb9b91ce8ad17.jar:?]
        at net.minecraft.server.packs.repository.Pack.readPackInfo(Pack.java:71) ~[?:?]
        at net.minecraft.server.packs.repository.Pack.readMetaAndCreate(Pack.java:47) ~[?:?]
        at net.fabricmc.fabric.impl.resource.loader.ModResourcePackCreator.loadPacks(ModResourcePackCreator.java:82) ~[fabric-resource-loader-v0-0.11.9+132c48c177-f47fb9b91ce8ad17.jar:?]
        at net.fabricmc.fabric.impl.resource.loader.ModResourcePackUtil.createDefaultDataConfiguration(ModResourcePackUtil.java:118) ~[fabric-resource-loader-v0-0.11.9+132c48c177-f47fb9b91ce8ad17.jar:?]
        at net.minecraft.server.dedicated.DedicatedServerProperties.redirect$zni000$fabric-resource-loader-v0$replaceDefaultDataConfiguration(DedicatedServerProperties.java:532) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServerProperties.<init>(DedicatedServerProperties.java:130) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServerProperties.fromFile(DedicatedServerProperties.java:137) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServerSettings.<init>(DedicatedServerSettings.java:12) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:115) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
        ... 4 more 
 ```
Idk why it crash, maybe a mod imcompat?

**Comment by jpenilla** [comment]
Please open a new issue if this is reproducible without cardboard
