### ISSUE TITLE
Cannot initialize mappings at preLaunch

### ISSUE THREAD

**Issue by rvbsm** [jpenilla/better-fabric-console#29]
**Minecraft Version:** 1.20.1
**Fabric Loader:** 0.14.22
**Fabric API:** 0.87.0+1.20.1
**Better Fabric Console:** 1.1.6

upd: Removing MemoryLeaksFix fixes this issue

[**Full log**](https://mclo.gs/AEnhg1E)

<details>
<summary>Stacktrace</summary>

```java
[14:35:57] [main/INFO]: Initializing Better Fabric Console...
[14:35:57] [main/INFO]: Initializing Better Fabric Console mappings...
[14:35:57] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.2.0-beta.10).
[14:35:57] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'better-fabric-console'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-launcher.jar:0.11.2]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'better-fabric-console'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.22.jar:?]
	... 4 more
Caused by: java.lang.ExceptionInInitializerError
	at xyz.jpenilla.betterfabricconsole.remap.MappingsCache.<clinit>(MappingsCache.java:46) ~[better-fabric-console-mc1.20.1-1.1.6.jar:?]
	at xyz.jpenilla.betterfabricconsole.BetterFabricConsolePreLaunch.createRemapper(BetterFabricConsolePreLaunch.java:118) ~[better-fabric-console-mc1.20.1-1.1.6.jar:?]
	at xyz.jpenilla.betterfabricconsole.BetterFabricConsolePreLaunch.initConsole(BetterFabricConsolePreLaunch.java:104) ~[better-fabric-console-mc1.20.1-1.1.6.jar:?]
	at xyz.jpenilla.betterfabricconsole.BetterFabricConsolePreLaunch.onPreLaunch(BetterFabricConsolePreLaunch.java:74) ~[better-fabric-console-mc1.20.1-1.1.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.22.jar:?]
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_155 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_3797.<init>(class_3797.java:37) ~[server-intermediary.jar:?]
	at net.minecraft.class_3797.<clinit>(class_3797.java:21) ~[server-intermediary.jar:?]
	at xyz.jpenilla.betterfabricconsole.remap.MappingsCache.<clinit>(MappingsCache.java:46) ~[better-fabric-console-mc1.20.1-1.1.6.jar:?]
	at xyz.jpenilla.betterfabricconsole.BetterFabricConsolePreLaunch.createRemapper(BetterFabricConsolePreLaunch.java:118) ~[better-fabric-console-mc1.20.1-1.1.6.jar:?]
	at xyz.jpenilla.betterfabricconsole.BetterFabricConsolePreLaunch.initConsole(BetterFabricConsolePreLaunch.java:104) ~[better-fabric-console-mc1.20.1-1.1.6.jar:?]
	at xyz.jpenilla.betterfabricconsole.BetterFabricConsolePreLaunch.onPreLaunch(BetterFabricConsolePreLaunch.java:74) ~[better-fabric-console-mc1.20.1-1.1.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.22.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_3797.<init>(class_3797.java:37) ~[server-intermediary.jar:?]
	at net.minecraft.class_3797.<clinit>(class_3797.java:21) ~[server-intermediary.jar:?]
	at xyz.jpenilla.betterfabricconsole.remap.MappingsCache.<clinit>(MappingsCache.java:46) ~[better-fabric-console-mc1.20.1-1.1.6.jar:?]
	at xyz.jpenilla.betterfabricconsole.BetterFabricConsolePreLaunch.createRemapper(BetterFabricConsolePreLaunch.java:118) ~[better-fabric-console-mc1.20.1-1.1.6.jar:?]
	at xyz.jpenilla.betterfabricconsole.BetterFabricConsolePreLaunch.initConsole(BetterFabricConsolePreLaunch.java:104) ~[better-fabric-console-mc1.20.1-1.1.6.jar:?]
	at xyz.jpenilla.betterfabricconsole.BetterFabricConsolePreLaunch.onPreLaunch(BetterFabricConsolePreLaunch.java:74) ~[better-fabric-console-mc1.20.1-1.1.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.22.jar:?]
	... 4 more
Caused by: java.lang.ClassCastException: class com.llamalad7.mixinextras.lib.apache.commons.tuple.ImmutablePair cannot be cast to class org.apache.commons.lang3.tuple.Pair (com.llamalad7.mixinextras.lib.apache.commons.tuple.ImmutablePair and org.apache.commons.lang3.tuple.Pair are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @5e5792a0)
	at ca.fxco.memoryleakfix.config.mixinExtension.UnMixinExtension.preApply(UnMixinExtension.java:23) ~[memoryleakfix-fabric-1.17+-1.1.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.preApply(Extensions.java:156) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.preApply(TargetClassContext.java:413) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:401) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_3797.<init>(class_3797.java:37) ~[server-intermediary.jar:?]
	at net.minecraft.class_3797.<clinit>(class_3797.java:21) ~[server-intermediary.jar:?]
	at xyz.jpenilla.betterfabricconsole.remap.MappingsCache.<clinit>(MappingsCache.java:46) ~[better-fabric-console-mc1.20.1-1.1.6.jar:?]
	at xyz.jpenilla.betterfabricconsole.BetterFabricConsolePreLaunch.createRemapper(BetterFabricConsolePreLaunch.java:118) ~[better-fabric-console-mc1.20.1-1.1.6.jar:?]
	at xyz.jpenilla.betterfabricconsole.BetterFabricConsolePreLaunch.initConsole(BetterFabricConsolePreLaunch.java:104) ~[better-fabric-console-mc1.20.1-1.1.6.jar:?]
	at xyz.jpenilla.betterfabricconsole.BetterFabricConsolePreLaunch.onPreLaunch(BetterFabricConsolePreLaunch.java:74) ~[better-fabric-console-mc1.20.1-1.1.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.22.jar:?]
	... 4 more
```
<details>

**Comment by jpenilla** [comment]
I think this is technically something that should be addressed from the `better-fabric-console` side, however [this PR](https://github.com/fxmorin/MemoryLeakFix/pull/138) looks like it might be related. Could you try with [this build](https://github.com/fxmorin/MemoryLeakFix/suites/15513918809/artifacts/885792074) of MemoryLeakFix?

**Comment by rvbsm** [comment]
> Could you try with [this build](https://github.com/fxmorin/MemoryLeakFix/suites/15513918809/artifacts/885792074) of MemoryLeakFix?

With this build, the server launched with no errors, so I'll wait for MemoryLeakFix to release it. Thanks!
