### ISSUE TITLE
When a player is killed with an enchanted weapon they do not drop items or get death message.

### ISSUE THREAD

**Issue by FifthTundraG** [jpenilla/better-fabric-console#46]
This issue was originally created on the [adventure-platform-fabric](https://github.com/KyoriPowered/adventure-platform-fabric) repository (which is a dependency for this mod). See the original issue here: https://github.com/KyoriPowered/adventure-platform-fabric/issues/145.

The primary issue here is that when a player is killed with an enchanted and named item (command example: `/give @a diamond_sword[minecraft:enchantments={sharpness:255},minecraft:custom_name="death"]`), the player's items will not drop on the ground, alongside the player not receiving them when they respawn (the items are erased). A death message will also not be shown in chat. When this happens, the following error is thrown in the console
```[23:09:52 ERROR] [Server thread]: [ServerPacketListener] Failed to handle packet net.minecraft.network.protocol.game.ServerboundInteractPacket@7bdbea3, suppressing error
com.google.gson.JsonParseException: Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]
	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
	at net.kyori.adventure.platform.fabric.impl.NonWrappingComponentSerializer.deserialize(NonWrappingComponentSerializer.java:66) ~[adventure-platform-fabric-5.14.0.jar:?]
	at net.minecraft.network.chat.Component.asComponent(Component.java:544) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.dedicated.DedicatedServer.sendSystemMessage(DedicatedServer.java:753) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.players.PlayerList.broadcastSystemMessage(PlayerList.java:758) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.players.PlayerList.broadcastSystemMessage(PlayerList.java:754) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:680) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1188) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:888) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:774) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1180) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:1636) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$1.onAttack(ServerGamePacketListenerImpl.java:1590) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:88) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:1550) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:75) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:38) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.network.protocol.PacketUtils.method_11072(PacketUtils.java:27) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.TickTask.run(TickTask.java:17) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:142) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:875) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:208) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:116) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:858) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:852) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:126) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:824) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:829) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:719) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:279) ~[minecraft-merged-8e1dd4a176-1.21-loom.mappings.1_21.layered+hash.2198-v2.jar:?]
```
	
It's worth noting that although the stacktrace mentions `net.kyori.adventure.platform.fabric`, as @MiniDigger stated in the original issue:

> adventure is only a library for displaying chat, for varius reasons it has to hook into the message sending pipeline. this is most likely not caused by adventure (or adventure-platform-fabric)

Another issue similarly related to the last one that @RedOptic pointed out is that when executing a `/give` command for an enchanted item (e.x `/give @s diamond_sword[minecraft:enchantments={sharpness:255}]`, the following error will appear in chat:
![image](https://github.com/jpenilla/better-fabric-console/assets/117035030/31d5ed2f-8b8e-48f5-b61a-46625996c115)
Unlike previously, when `/give`-ing an enchanted item an error does not appear in the server console, only on the client-side.

Despite not mentioning Better Fabric Console in the stacktrace, when running `adventure-platform-fabric` and testing this issue, nothing unusual occurred, and killing other players worked as expected. When running Better Fabric Console, this issue was immediately prevalent, despite the issue and this mod's function not seeming to relate in any meaningful way. As such, I can only assume that this mod (or maybe another one of its dependencies?) is the root cause of the issue.

**Comment by FifthTundraG** [comment]
See https://github.com/KyoriPowered/adventure-platform-fabric/issues/145
