### ISSUE TITLE
Server crashes on death of a player using an enchanted weapon

### ISSUE THREAD

**Issue by gjorgdy** [jpenilla/better-fabric-console#50]
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2024-07-11 20:58:47
Description: Ticking entity

com.google.gson.JsonParseException: Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]; Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]; Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]; Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]; Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]
	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287)
	at net.kyori.adventure.platform.fabric.impl.NonWrappingComponentSerializer.deserialize(NonWrappingComponentSerializer.java:66)
	at net.minecraft.network.chat.Component.asComponent(Component.java:544)
	at net.minecraft.server.dedicated.DedicatedServer.sendSystemMessage(DedicatedServer.java:753)
	at net.minecraft.server.players.PlayerList.broadcastSystemMessage(PlayerList.java:796)
	at net.minecraft.server.players.PlayerList.broadcastSystemMessage(PlayerList.java:792)
	at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:710)
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1252)
	at net.minecraft.world.entity.player.Player.hurt(Player.java:977)
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:811)
	at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:402)
	at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:208)
	at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:182)
	at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:248)
	at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:74)
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:770)
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:498)
	at net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:408)
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:372)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1021)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:299)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:912)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:281)
	at java.base@22/java.lang.Thread.run(Thread.java:1570)

**Comment by jpenilla** [comment]
Duplicate https://github.com/jpenilla/better-fabric-console/issues/46
