### ISSUE TITLE
Crashes on server startup for me

### ISSUE THREAD

**Issue by Justsnoopy30** [jpenilla/better-fabric-console#7]
Log:
```Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[15:44:27] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.4
[15:44:27] [ForkJoinPool-1-worker-12/WARN]: The mod "create" contains invalid entries in its mod json:
- Unsupported root entry "/* you need to enable this if you want to run datagen because yes */ provides" at line 1 column 735
[15:44:27] [ForkJoinPool-1-worker-12/WARN]: Mod create uses the version mc1.18.2_v0.4.1+548 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'mc1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[15:44:27] [ForkJoinPool-1-worker-15/WARN]: Mod plan uses the version 5.4 build 1633 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '4 build 1633'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[15:44:27] [ForkJoinPool-1-worker-11/WARN]: Mod registrate-fabric uses the version MC1.18.2-1.0.x which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'MC1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[15:44:27] [main/INFO]: Loading 180 mods:
	- advanced_runtime_resource_pack 0.5.7 via phonos
	- adventure-platform-fabric 5.2.1 via better-fabric-console
	- architectury 4.4.54
	- badpackets 0.1.2
	- bclib 1.4.5
	- beacon 0.7.3
	- better-fabric-console 1.0.4
	- betterend 1.1.0
	- bettermineshafts 1.18.2-Fabric-2.1.1
	- betterstrongholds 1.18.2-Fabric-2.1.1
	- bitsandchisels 2.6.8
	- blue_endless_jankson 1.2.1 via jankson
	- campanion 3.0.4
	- cardinal-components-base 4.1.3 via trinkets
	- cardinal-components-entity 4.1.3 via trinkets
	- carpet 1.4.69
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- com_electronwill_night-config_core 3.6.5 via servercore
	- com_electronwill_night-config_toml 3.6.5 via servercore
	- com_github_llamalad7_mixinextras 0.0.9 via porting_lib
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_moandjiezana_toml_toml4j 0.7.2 via servertick
	- com_typesafe_config 1.4.2 via confabricate
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- confabricate 3.0.0-SNAPSHOT+4.1.2 via better-fabric-console
	- create mc1.18.2_v0.4.1+548
	- dml-refabricated 1.18.2
	- dml-refabricated-base 1.18.2 via dml-refabricated
	- dml-refabricated-events 1.18.2 via dml-refabricated
	- dml-refabricated-modular-armor 1.18.2 via dml-refabricated
	- dml-refabricated-rei 1.18.2 via dml-refabricated
	- dripstone_fluid_lib 1.2.0 via milk
	- fabric 0.51.1+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-data-generation-api-v1 2.0.7+6d3e563660 via registrate-fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-language-kotlin 1.7.2+kotlin.1.6.20
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabricloader 0.14.4
	- fake-player-api 0.3.0 via create
	- feature_nbt_deadlock_be_gone 2.0.0+1.18.2-rc1
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via patchouli
	- forge_tags 2.1 via registrate-fabric
	- forgeconfigapiport 3.2.0 via create
	- gateofbabylon 1.7.0-1.18.2
	- incendium 5.0.3
	- indrev 1.14.0-BETA
	- inmis 2.5.3-1.18.2
	- invview 1.4.8-1.18+
	- io_leangen_geantyref_geantyref 1.3.13 via beacon
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- jsonem 0.1.1 via phonos
	- kibe 1.9.7-BETA+1.18
	- kilo_essentials 1.21.0-ModernTimes-1.18.2-rc1
	- krypton 0.1.9
	- ktdatataglib 1.6.5+1.18.2 via dml-refabricated
	- kubejs 1802.5.1-build.394
	- lazydfu 0.1.2
	- ledger 1.2.4
	- libblockattributes_core 0.10.0 via indrev
	- libblockattributes_fluids 0.10.0 via indrev
	- libblockattributes_items 0.10.0 via indrev
	- libgui 5.3.2+1.18.2 via indrev
	- libninepatch 1.1.0 via libgui
	- lithium 0.7.9-SNAPSHOT
	- luckperms 5.4.12
	- magna 1.7.0-1.18-pre1 via indrev
	- megane 7.5.1
	- megane-api 7.1.0 via megane
	- megane-fabric-transfer 7.1.0 via megane
	- megane-industrial-revolution 7.1.0 via megane
	- megane-kibe 7.1.0 via megane
	- megane-lib-block-attributes 7.1.0 via megane
	- megane-reborn-energy 7.0.0 via megane
	- megane-runtime 7.2.0 via megane
	- megane-vanilla 7.1.1 via megane
	- milk 0.3.0 via create
	- minecraft 1.18.2
	- mm 2.3 via porting_lib
	- mostructures 1.4.2+1.18.2
	- mtr 1.18.2-3.0.0
	- net_fabricmc_mapping-io 0.3.0 via better-fabric-console
	- net_java_dev_jna_jna 5.8.0 via beacon
	- net_java_dev_jna_jna-platform 5.8.0 via beacon
	- net_kyori_adventure-api 4.10.1 via adventure-platform-fabric
	- net_kyori_adventure-key 4.10.1 via adventure-platform-fabric
	- net_kyori_adventure-platform-api 4.1.0 via adventure-platform-fabric
	- net_kyori_adventure-text-minimessage 4.10.1 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-gson 4.10.1 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-legacy 4.10.1 via better-fabric-console
	- net_kyori_adventure-text-serializer-plain 4.10.1 via adventure-platform-fabric
	- net_kyori_examination-api 1.3.0 via adventure-platform-fabric
	- net_kyori_examination-string 1.3.0 via adventure-platform-fabric
	- net_minecrell_terminalconsoleappender 1.2.0 via beacon
	- not-that-cc 1.0
	- omega-config 1.2.3-1.18.1 via mostructures
	- org_fusesource_jansi_jansi 2.4.0 via better-fabric-console
	- org_jetbrains_kotlin_kotlin-reflect 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
	- org_jline_jline 3.21.0 via better-fabric-console
	- org_jline_jline-terminal-jansi 3.21.0 via better-fabric-console
	- org_jline_jline-terminal-jna 3.20.0 via beacon
	- org_spongepowered_configurate-core 4.1.2 via confabricate
	- org_spongepowered_configurate-extra-dfu4 4.1.2 via confabricate
	- org_spongepowered_configurate-gson 4.1.2 via confabricate
	- org_spongepowered_configurate-hocon 4.1.2 via confabricate
	- org_spongepowered_configurate-yaml 4.1.1 via beacon
	- org_yaml_snakeyaml 1.28 via beacon
	- packet_tweaker 0.2.0+1.18-pre1 via server_translations_api
	- patchouli 1.18.2-67-FABRIC
	- phonos 0.3+1.18.2
	- placeholder-api 1.1.3+1.17.1 via servercore
	- plan 5.4 build 1633
	- player_events 2.2.3
	- player_events_api 2.2.3 via player_events
	- playerabilitylib 1.5.0 via kibe
	- porting_lib 0.2.0+1.18.2.7714a8d via create
	- reach-entity-attributes 2.1.1 via campanion
	- registrate-fabric MC1.18.2-1.0.x via create
	- repurposed_structures 4.1.6+1.18.2
	- rhino 1801.1.9-build.135
	- roughlyenoughitems 8.1.9999
	- seedfix 1.0.2
	- server_translations_api 1.4.9+1.18.2-rc1 via ledger
	- servercore 1.2.9-1.18.2
	- servertick 1.6
	- sgui 1.0.0-rc6+1.18-pre5 via invview
	- spark 1.9.1
	- stacc 1.2.3 via bitsandchisels
	- starlight 1.0.2+fabric.a920f5a
	- step-height-entity-attribute 1.0.0 via indrev
	- tcc 1.0.1
	- team_reborn_energy 2.0.0-beta1 via indrev
	- terralith 2.2
	- trinkets 3.3.0
	- worldedit 7.2.10-SNAPSHOT+6109-1734dc7
	- wthit 4.10.1
	- xaerominimapfair 22.6.1
	- xaeroworldmap 1.20.7
	- yungsapi 1.18.2-Fabric-2.0.8
	- yungsbridges 1.18.2-Fabric-2.1.0
[15:44:27] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/justsnoopy30/Projects/Minecraft%20Servers/Fabric/Modded/libraries/net/fabricmc/sponge-mixin/0.11.3+mixin.0.8.5/sponge-mixin-0.11.3+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[15:44:27] [main/INFO]: Compatibility level set to JAVA_16
[15:44:27] [main/INFO]: Compatibility level set to JAVA_17
[15:44:27] [main/WARN]: Reference map 'confabricate-accessor-refmap.json' for confabricate.accessor.mixins.json could not be read. If this is a development environment you can ignore this message
[15:44:27] [main/INFO]: Loaded configuration file for Lithium: 100 options available, 3 override(s) found
[15:44:27] [main/WARN]: Reference map 'rhino-fabric-refmap.json' for rhino.mixins.json could not be read. If this is a development environment you can ignore this message
[15:44:27] [main/WARN]: Reference map 'yungsbridges.refmap.json' for yungsbridges.mixins.json could not be read. If this is a development environment you can ignore this message
[15:44:27] [main/WARN]: Reference map 'yungsbridges.refmap.json' for yungsbridges_fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[15:44:28] [main/WARN]: Error loading class: net/minecraft/class_1007 (java.lang.ClassNotFoundException: net/minecraft/class_1007)
[15:44:28] [main/WARN]: @Mixin target net.minecraft.class_1007 was not found inmis.mixins.json:client.PlayerEntityFeatureMixin from mod inmis
[15:44:28] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[15:44:28] [main/WARN]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by mods [servercore]) disables it and children
[15:44:28] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[15:44:28] [main/WARN]: Error loading class: net/minecraft/class_5616 (java.lang.ClassNotFoundException: net/minecraft/class_5616)
[15:44:28] [main/WARN]: @Mixin target net.minecraft.class_5616 was not found registrate-fabric.mixins.json:accessor.BlockEntityRenderersAccessor from mod registrate-fabric
[15:44:28] [main/WARN]: [carpet] detected, disabling UPDATE mixin com.sk89q.worldedit.fabric.mixin.MixinLevelChunkSetBlockHook
[15:44:28] [main/INFO]: I used the json to destroy the json
[15:44:29] [main/WARN]: Method overwrite conflict for getLanguage in worldedit.mixins.json:MixinServerPlayer from mod worldedit, previously written by carpet.mixins.ServerPlayer_scarpetEventMixin. Skipping method.
[15:44:30] [main/WARN]: @ModifyConstant conflict. Skipping yungsapi.mixins.json:IncreaseStructureWeightLimitMixin from mod yungsapi->@ModifyConstant::yungsapi_increaseWeightLimit(I)I with priority 1000, already redirected by repurposed_structures.mixins.json:structures.StructurePoolMixin from mod repurposed_structures->@ModifyConstant::repurposedstructures_increaseWeightLimitProd(I)I with priority 1000
[15:44:31] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'net.kyori.adventure.util.Codec net.kyori.adventure.util.Codec.codec(net.kyori.adventure.util.Codec$Decoder, net.kyori.adventure.util.Codec$Encoder)'
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:454) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.4.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:67) [fabric-loader-0.14.4.jar:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.util.Codec net.kyori.adventure.util.Codec.codec(net.kyori.adventure.util.Codec$Decoder, net.kyori.adventure.util.Codec$Encoder)'
	at net.kyori.adventure.platform.fabric.impl.NBTLegacyHoverEventSerializer.<clinit>(NBTLegacyHoverEventSerializer.java:43) ~[adventure-platform-fabric-5.2.1-ebaac98651ff0672.jar:?]
	at net.kyori.adventure.platform.fabric.impl.service.GsonComponentSerializerProviderImpl.lambda$builder$0(GsonComponentSerializerProviderImpl.java:50) ~[adventure-platform-fabric-5.2.1-ebaac98651ff0672.jar:?]
	at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl$BuilderImpl.<init>(GsonComponentSerializerImpl.java:117) ~[kilo_essentials-1.21.0-ModernTimes-1.18.2-rc1.jar:?]
	at net.kyori.adventure.text.serializer.gson.GsonComponentSerializer.builder(GsonComponentSerializer.java:77) ~[kilo_essentials-1.21.0-ModernTimes-1.18.2-rc1.jar:?]
	at net.kyori.adventure.platform.fabric.impl.service.GsonComponentSerializerProviderImpl.gson(GsonComponentSerializerProviderImpl.java:34) ~[adventure-platform-fabric-5.2.1-ebaac98651ff0672.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl$Instances.<clinit>(GsonComponentSerializerImpl.java:48) ~[kilo_essentials-1.21.0-ModernTimes-1.18.2-rc1.jar:?]
	at net.kyori.adventure.text.serializer.gson.GsonComponentSerializer.gson(GsonComponentSerializer.java:54) ~[kilo_essentials-1.21.0-ModernTimes-1.18.2-rc1.jar:?]
	at net.minecraft.class_2561$class_2562.handler$zdi000$adventure$injectGson(class_2561.java:1064) ~[server-intermediary.jar:?]
	at net.minecraft.class_2561$class_2562.method_10878(class_2561.java:133) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_656(class_156.java:430) ~[server-intermediary.jar:?]
	at net.minecraft.class_2561$class_2562.<clinit>(class_2561.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.method_7977(class_1799.java:638) ~[server-intermediary.jar:?]
	at net.minecraft.class_3765.method_16515(class_3765.java:702) ~[server-intermediary.jar:?]
	at net.minecraft.class_3763.<clinit>(class_3763.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.class_5135.<clinit>(class_5135.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_17598(class_2966.java:137) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:99) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) ~[fabric-loader-0.14.4.jar:?]
	... 7 more
```

**Comment by jpenilla** [comment]
Is this reproducible with only fabric-api and squaremap?

**Comment by jpenilla** [comment]
Closing due to lack of response from reporter
